### ISSUE TITLE
有一行运行错误

### ISSUE THREAD

**Issue by XianwuLin** [rainyear/cix-extractor-py#1]
File "C:\Users\Victor\Desktop\123.py", line 50, in <lambda>
    self.cblocks = list(map(lambda x,y: x+y, self.textLens[i : lines-1-self.bloc
kSize+i], self.cblocks))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by VictorXianwu** [comment]
你的运行环境是py3？

**Comment by XianwuLin** [comment]
我觉得py2.7需要修改两个地方：

``` python
self.cblocks = list(map(lambda x,y: str(x)+str(y), self.textLens[i : lines-1-self.blockSize+i], self.cblocks))
print ext.getContext().encode("utf-8")
```

**Comment by rainyear** [comment]
@VictorXianwu 

`map`这一行的错误是因为两个list的长度不一样，已改正 :smiley:
